package com.ssm.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ssm.domain.Dict;
import com.ssm.domain.DictExample;

public interface DictMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	int insert(Dict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	int insertSelective(Dict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	List<Dict> selectByExample(DictExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	Dict selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	int updateByPrimaryKeySelective(Dict record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	int updateByPrimaryKey(Dict record);

	Dict selectByPCodeAndCode(@Param("parentCode") String parentCode, @Param("code") String code);

	List<Dict> findByPcode(@Param("parentCode") String parentCode);
}