package com.ssm.dao;

import com.ssm.domain.Roles;

public interface RolesMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	int insert(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	int insertSelective(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	Roles selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	int updateByPrimaryKeySelective(Roles record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	int updateByPrimaryKey(Roles record);
}