package com.ssm.domain;

import java.io.Serializable;
import java.util.Date;

public class Dict implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.id
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.code
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private String code;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.parentCode
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private String parentCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.sort
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private Byte sort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.name
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column dict.createTime
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table dict
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.id
	 *
	 * @return the value of dict.id
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.id
	 *
	 * @param id
	 *            the value for dict.id
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.code
	 *
	 * @return the value of dict.code
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.code
	 *
	 * @param code
	 *            the value for dict.code
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.parentCode
	 *
	 * @return the value of dict.parentCode
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public String getParentCode() {
		return parentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.parentCode
	 *
	 * @param parentCode
	 *            the value for dict.parentCode
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setParentCode(String parentCode) {
		this.parentCode = parentCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.sort
	 *
	 * @return the value of dict.sort
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public Byte getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.sort
	 *
	 * @param sort
	 *            the value for dict.sort
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setSort(Byte sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.name
	 *
	 * @return the value of dict.name
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.name
	 *
	 * @param name
	 *            the value for dict.name
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column dict.createTime
	 *
	 * @return the value of dict.createTime
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column dict.createTime
	 *
	 * @param createTime
	 *            the value for dict.createTime
	 *
	 * @mbggenerated Wed Sep 28 14:57:04 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Override
	public String toString() {
		return "Dict [id=" + id + ", code=" + code + ", parentCode=" + parentCode + ", sort=" + sort + ", name=" + name
				+ ", createTime=" + createTime + "]";
	}

}