package com.ssm.domain;

import java.io.Serializable;
import java.util.Date;

public class Roles implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.id
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.role
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String role;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.desc
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String desc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.resource_ids
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String resourceIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.createTime
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_roles.available
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Short available;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table sys_roles
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.id
	 * 
	 * @return the value of sys_roles.id
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.id
	 * 
	 * @param id
	 *            the value for sys_roles.id
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.role
	 * 
	 * @return the value of sys_roles.role
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.role
	 * 
	 * @param role
	 *            the value for sys_roles.role
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setRole(String role) {
		this.role = role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.desc
	 * 
	 * @return the value of sys_roles.desc
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.desc
	 * 
	 * @param desc
	 *            the value for sys_roles.desc
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setDesc(String desc) {
		this.desc = desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.resource_ids
	 * 
	 * @return the value of sys_roles.resource_ids
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getResourceIds() {
		return resourceIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.resource_ids
	 * 
	 * @param resourceIds
	 *            the value for sys_roles.resource_ids
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setResourceIds(String resourceIds) {
		this.resourceIds = resourceIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.createTime
	 * 
	 * @return the value of sys_roles.createTime
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.createTime
	 * 
	 * @param createTime
	 *            the value for sys_roles.createTime
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_roles.available
	 * 
	 * @return the value of sys_roles.available
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Short getAvailable() {
		return available;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_roles.available
	 * 
	 * @param available
	 *            the value for sys_roles.available
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setAvailable(Short available) {
		this.available = available;
	}
}