package com.ssm.domain;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.id
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.username
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.password
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.salt
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String salt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.role_ids
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private String roleIds;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.islock
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Short islock;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column sys_users.createTime
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table sys_users
	 * 
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.id
	 * 
	 * @return the value of sys_users.id
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.id
	 * 
	 * @param id
	 *            the value for sys_users.id
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.username
	 * 
	 * @return the value of sys_users.username
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.username
	 * 
	 * @param username
	 *            the value for sys_users.username
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.password
	 * 
	 * @return the value of sys_users.password
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.password
	 * 
	 * @param password
	 *            the value for sys_users.password
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.salt
	 * 
	 * @return the value of sys_users.salt
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.salt
	 * 
	 * @param salt
	 *            the value for sys_users.salt
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.role_ids
	 * 
	 * @return the value of sys_users.role_ids
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public String getRoleIds() {
		return roleIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.role_ids
	 * 
	 * @param roleIds
	 *            the value for sys_users.role_ids
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setRoleIds(String roleIds) {
		this.roleIds = roleIds;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.islock
	 * 
	 * @return the value of sys_users.islock
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Short getIslock() {
		return islock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.islock
	 * 
	 * @param islock
	 *            the value for sys_users.islock
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setIslock(Short islock) {
		this.islock = islock;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column sys_users.createTime
	 * 
	 * @return the value of sys_users.createTime
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column sys_users.createTime
	 * 
	 * @param createTime
	 *            the value for sys_users.createTime
	 * @mbggenerated Thu Aug 25 17:46:27 CST 2016
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}